name: Messaggio semplice

on: [push]

jobs:
  stampa-messaggio:
    runs-on: self-hosted   # mantiene l'ambiente di esecuzione

    steps:
      - name: Stampa un messaggio
        run: echo "Sto girando sul runner self-hosted Windows"
