name: Test semplice

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Stampa un messaggio
        run: echo "Ciao dal tuo primo GitHub Action!"
